### ISSUE TITLE
Terrain Brush for Meshes gives "AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

### ISSUE THREAD

**Issue by AaronTrip** [blackears/blenderTerrainSculpt#1]
I purchased this tool and started following along with your video tutorials to sculpt terrain. Immediately after trying to I was unable to use it to do anything because of this error, which does not allow me to sculpt.
![Blender terrain tool error](https://github.com/blackears/blenderTerrainSculpt/assets/43454780/66a22201-aaaf-49a4-88a5-2076cc1d46fa)

**Comment by AaronTrip** [comment]
I am using Blender 4.1

**Comment by AaronTrip** [comment]
Reverted to blender 3.6 and that version still works! Just looks like it's broken for 4.0 and up

**Comment by blackears** [comment]
I've checked in an update.  Version 1.0.7 should fix this bug.
