### ISSUE TITLE
Install / activate issue

### ISSUE THREAD

**Issue by davemariannn** [blackears/blenderTerrainSculpt#4]
Hi!

Not sure if I did something wrong, but I get an error trying to activate the plugin in Blender.

I'm using Blender 4.2 (installed via Steam), on Debian stable. Downloaded the .zip from Github, ran MakeDeploy.py and imported the .zip from the deploy folder into Blender.

Following message appears in console:

> bpy.context.space_data.system_folders_active = 5
> Python: Traceback (most recent call last):
>   File "/home/dave/.steam/debian-installation/steamapps/common/Blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 1302, in execute
>     cmd_batch = self.exec_command_iter(is_modal)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dave/.steam/debian-installation/steamapps/common/Blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2338, in exec_command_iter
>     self.exec_legacy(source_filepath)
>   File "/home/dave/.steam/debian-installation/steamapps/common/Blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2465, in exec_legacy
>     bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
>   File "/home/dave/.steam/debian-installation/steamapps/common/Blender/4.2/scripts/startup/bl_operators/userpref.py", line 780, in execute
>     bpy.ops.preferences.addon_enable(module=mod.__name__)
>   File "/home/dave/.steam/debian-installation/steamapps/common/Blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
>     ret = _op_call(self.idname_py(), kw)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Error: No module named 'terrainSculptTools.operators.TerrainSculptMeshBrush'
> No module named 'terrainSculptTools.operators.TerrainSculptMeshBrush'

![Screenshot from 2024-07-22 10-41-17](https://github.com/user-attachments/assets/43021da3-221f-43af-be6c-1bbe618071b6)

Loved the idea of the plugin! Hope I can get it to work and sry if I made some obvious error. 
Thanks already!

**Comment by blackears** [comment]
I think the issue may have been due to one of the filenames having the wrong case, which would explain why it works on Windows and not Linux.  Could you try again  with the latest code and let me know if you have the issue?

**Comment by davemariannn** [comment]
Hi!
Yes, seems like this was the issue! New patch let me install and use the tool out of the box! Thanks!
