### ISSUE TITLE
Doesn't work on Blender 4.2

### ISSUE THREAD

**Issue by bauerbach** [blackears/blenderTerrainSculpt#5]
The sculpting tools don't do anything at all. I suspect it's because I'm on Blender 4.2 and the plugin page only lists versions up to Blender 4.1. There are no errors or anything; it's just that nothing happens when I use the brushes.

**Comment by blackears** [comment]
I just tested on my Blender 4.2.0 installation.  It is working for me.  Make sure to press the Terrain Brush for Meshes button before you start drawing - this is necessary to start the tool working.

If this is still not working, please check to console for any error messages and report them here.  Also, please describe exactly what steps you are taking to use the tool, what you are observing and what you are expecting to happen.
